endroid_qr_code:
    builder:
        writer: Endroid\QrCode\Writer\PngWriter
        options:
            Endroid\QrCode\QrCodeInterface:
                errorCorrectionLevel: 'low'
            Endroid\QrCode\Writer\ImageWriterInterface:
                size: 300
                margin: 10
            Endroid\QrCode\Writer\Vali...
                validate: false
